### PR TITLE
Update modelrunner.py

### PR DESCRIPTION
**Pull request by aphelionz**
I believe these changes are needed to run against the latest nupic

### CODE REVIEW

**Comment by rhyolight** [comment]
Awesome, thanks!

**Comment by rhyolight** [comment]
ok this sucks, but the River View instance at data.numenta.org has been broken for ages. So if you're going to use this, you'll need to interface with some other streaming agent, or start your own river view instance.

**Comment by aphelionz** [comment]
Aha! It did "work" for me after I made those updates. I got a lot of entries into two MySQL tables, but I admit that I don't know enough about this yet to validate whether or not it was successful or not. So, to my untrained eye, it seemed to work!

BTW, what I'm working on is marine audio data collected from Hydrophones. I can share in much more detail what's involved. It might very well warrant its own river view instance.

**Comment by rhyolight** [comment]
You might want to look into https://github.com/htm-community/influx.htm instead. It allows you to stream time-series data into influxdb, which is a time-series database, and train HTM models over it at arbitrary starting locations. See https://discourse.numenta.org/t/nupic-influxdb/1594/2?u=rhyolight

**Comment by aphelionz** [comment]
Will do, thanks!

**Pull request merged**
